application:
  interfaces:
    component:
      "*": bind(factory#component.*)
    webui:
      webui-by-id: bind(factory#factory.instances)
    configuration:
      "*": bind(factory#configuration.*)
  configuration:
    component.application: "ISP web UI on marathon"
    component.discoveryScript: /webui/discover.py
    component.discoverySchedule: "0/30 * * * * ? *"
  components:
    factory:
      type: scripted.ComponentFactory
      interfaces:
        configuration:
          marathonURL: configuration(string)
        apps:
          app-by-id: consume-signal(map<string,string>)
    scripting:
      type: reference.Service
      interfaces:
        scripting:
          execute: receive-command(string script, object arguments => object results)
    marathon:
      type: reference.Service
      interfaces:
        apps:
          app-by-id: publish-signal(map<string,string>)
  bindings:
    - [factory, marathon]
    - [factory, scripting]
