application:
  configuration:
    configuration.name: '/new-webui'
    configuration.service-port: 10200
  interfaces:
    configuration:
      "*": bind(application#configuration.*)
    ui:
      "*": bind(application#ui.*)
    compute:
      "*": bind(application#compute.*)
    control:
      "*": bind(application#control.*)
  components:
    application:
      type: scripted.Component
      configuration:
        factory.name: ISP web UI on marathon Factory
        factory.launchScript:           /webui/create.py
        factory.destroyScript:          /webui/destroy.py
        factory.healthCheckScript:      /webui/healthCheck.py
        factory.reconfigurationScript:  /webui/reconfigure.py
        factory.commandScripts:
            control.restart:            /webui/restart.py
            control.scale:              /webui/scale.py
      interfaces:
        configuration:
          name:
            type: configuration(string)
            name: Application name
          service-port:
            type: configuration(int)
            name: Service port
          cassandra-host:
            type: configuration(string)
            name: Cassandra host
          cassandra-port:
            type: configuration(int)
            name: Cassandra port
        ui:
          link:
            type: publish-signal(string)
            name: Application link
          load-balancer-port:
            type: publish-signal(string)
            name: LB port
          hosts:
            type: publish-signal(list<string>)
            name: Hosts
        compute:
          ram:
            type: publish-signal(string)
            name: RAM
          cpu:
            type: publish-signal(string)
            name: CPU
          disk:
            type: publish-signal(string)
            name: Disk
          instances:
            type: publish-signal(string)
            name: Instances
        control:
          restart:
            type: receive-command()
            name: Restart
          scale:
            type: receive-command(int instances)
            name: Scale application
            arguments:
              instances:
                name: Instances
                default: 2
